services:
  redis:
      image: redis:7-alpine
      container_name: laker-redis
      command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 5s
        timeout: 3s
        retries: 5
      restart: unless-stopped

  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    restart: unless-stopped
    environment:
      ORACLE_PWD: Bot#2023
      APP_USER: bot
      APP_USER_PASSWORD: Bot#2023
    ports:
      - "1521:1521"
    volumes:
      - laker_oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10

  # sshost-dummy:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dummy_sshost
  #   container_name: laker-sshost-dummy
  #   restart: unless-stopped
  #   ports:
  #     - "9000:9000"


  api:
    build: .
    container_name: laker-api
    restart: unless-stopped
    env_file: .env
    environment:
      DB_HOST: ${DB_HOST}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      oracle-db:
        condition: service_healthy
      # sshost-dummy:
      #   condition: service_started
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --workers 2"



volumes:
  laker_oracle_data:
  redis-data:
