"""empty message

Revision ID: 0a3054329f6f
Revises: 
Create Date: 2026-06-18 05:41:31.686237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a3054329f6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('plan_id', sa.String(length=20), nullable=False),
    sa.Column('carrier', sa.String(length=100), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('group_number', sa.String(length=20), nullable=True),
    sa.Column('rx_bin', sa.String(length=10), nullable=True),
    sa.Column('rx_pcn', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_plan_id'), 'plans', ['plan_id'], unique=True)
    op.create_table('revoked_access_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('token_hash', 'id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('members',
    sa.Column('member_id', sa.String(length=20), nullable=False, unique=True),
    sa.Column('subscriber_member_id', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('mi', sa.String(length=1), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.Column('ssn', sa.String(length=11), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('language_preference', sa.String(length=10), nullable=True),
    sa.Column('insured_id', sa.String(length=50), nullable=True),
    sa.Column('person_code', sa.String(length=5), nullable=False),
    sa.Column('family_position', sa.String(length=5), nullable=True),
    sa.Column('rel_code', sa.String(length=5), nullable=False),
    sa.Column('laker_pc', sa.String(length=20), nullable=True),
    sa.Column('prev_card_id', sa.String(length=50), nullable=True),
    sa.Column('cov_type', sa.Enum('CARDHOLDER', 'FAMILY', 'SPOUSE', 'DEPENDENT', name='coveragetype'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('plan_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscriber_member_id'], ['members.member_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_member_id'), 'members', ['member_id'], unique=True)
    op.create_index(op.f('ix_members_plan_id'), 'members', ['plan_id'], unique=False)
    op.create_index(op.f('ix_members_subscriber_member_id'), 'members', ['subscriber_member_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('token', sa.String(length=120), nullable=False),
    sa.Column('family_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('member_addresses',
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('address1', sa.String(length=255), nullable=True),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_addresses_member_id'), 'member_addresses', ['member_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_addresses_member_id'), table_name='member_addresses')
    op.drop_table('member_addresses')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_members_subscriber_member_id'), table_name='members')
    op.drop_index(op.f('ix_members_plan_id'), table_name='members')
    op.drop_index(op.f('ix_members_member_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('revoked_access_tokens')
    op.drop_index(op.f('ix_plans_plan_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
