"""fix revoked_access_tokens token_hash type

Revision ID: 0f6010a043ac
Revises: 36f4f9044a4c
Create Date: 2026-06-17 12:43:47.396112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f6010a043ac'
down_revision: Union[str, Sequence[str], None] = '36f4f9044a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('revoked_access_tokens', 'token_hash',
               existing_type=sa.UUID(),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('revoked_access_tokens', 'token_hash',
               existing_type=sa.String(length=64),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
