"""claim-search table-added-fields

Revision ID: 1e8919eea626
Revises: 5c7576d2f719
Create Date: 2026-06-19 09:05:19.624755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e8919eea626'
down_revision: Union[str, Sequence[str], None] = '5c7576d2f719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
