"""add additional pharmacy fields

Revision ID: 2d1fe5c6f3c8
Revises: 910dc407e12c
Create Date: 2026-08-14 07:34:24.648487

NOTE: This migration was originally autogenerated as a full `create_table`,
which fails with ORA-00955 because the `pharmacies` table already exists
(built by bf9bb90214b7 -> 2d27b194a8e4 -> 910dc407e12c using the OLD model,
before Oracle-native column names were added via mapped_column(name=...)).

Since no explicit `name=` was set on those older columns, SQLAlchemy sent
them unquoted and Oracle auto-uppercased them WHILE KEEPING UNDERSCORES
(e.g. `pharmacy_name` -> `PHARMACY_NAME`). This migration renames each of
those columns to the new Oracle-native name (e.g. `PHARMACY_NAME` ->
`PHARMACYNAME`) instead of recreating the table.

CAVEAT: this mapping was reconstructed from the model definitions and the
'add_column' migration history visible in this conversation, not from a
live `all_tab_columns` query against your actual dev DB. Before running,
it's worth spot-checking a few entries against:
    SELECT column_name FROM all_tab_columns WHERE table_name = 'PHARMACIES' ORDER BY column_id;
If any name here doesn't match reality, alter_column will fail loudly and
clearly (unknown column) rather than silently doing the wrong thing, so it's
safe to try and adjust.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2d1fe5c6f3c8'
down_revision: Union[str, Sequence[str], None] = '910dc407e12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (old Oracle column name, new Oracle column name) -- only pairs that actually differ
_RENAMES = [
    ("PHARMACY_NAME", "PHARMACYNAME"),
    ("PHARM_NAME2", "PHARMNAME2"),
    ("LEGAL_NAME", "LEGALNAME"),
    ("DOCTOR_NAME", "DOCTORNAME"),
    ("ADDRESS_LINE1", "PHARMADDR1"),
    ("ADDRESS_LINE2", "PHARMADDR2"),
    ("ADDRESS_LINE3", "PHARMADDR3"),
    ("CITY", "PHARMCITY"),
    ("STATE", "PHARMSTATE"),
    ("ZIP", "PHARMZIP"),
    ("COUNTY_FIPS_CODE", "COUNTYFIPSCODE"),
    ("VOTING_DISTRICT", "VOTINGDISTRICT"),
    ("MAIL_ADDR1", "MAILADDR1"),
    ("MAIL_ADDR2", "MAILADDR2"),
    ("MAIL_CITY", "MAILCITY"),
    ("MAIL_STATE", "MAILSTATE"),
    ("MAIL_ZIP", "MAILZIP"),
    ("PHONE_EXT", "PHARMPHONEEXT"),
    ("PHARM_EMAIL", "PHARMEMAIL"),
    ("HOSPICE_PHONE", "HOSPICEPHONE"),
    ("HOSPICE_FAX", "HOSPICEFAX"),
    ("CONTACT_FIRST_NAME", "CONTACTFIRSTNAME"),
    ("CONTACT_LAST_NAME", "CONTACTLASTNAME"),
    ("CONTACT_MI", "CONTACTMI"),
    ("CONTACT_TITLE", "CONTACTTITLE"),
    ("CONTACT_PHONE", "CONTACTPHONE"),
    ("CONTACT_PHONE_EXT", "CONTACTPHONEEXT"),
    ("CONTACT_EMAIL", "CONTACTEMAIL"),
    ("DISP_CLASS", "DISPCLASS"),
    ("DISP_TYPE", "DISPTYPE"),
    ("DISP_TYPE2", "DISPTYPE2"),
    ("DISP_TYPE3", "DISPTYPE3"),
    ("DIR_NAME", "DIRNAME"),
    ("DIR_CHAIN", "DIRCHAIN"),
    ("DIR_CLASS", "DIRCLASS"),
    ("FED_LICENCE", "FEDLICENCE"),
    ("FED_TIN", "FEDTIN"),
    ("FED_EXPIRATION_DATE", "FEDEXPIRATIONDATE"),
    ("STATE_LICENCE", "STATELICENCE"),
    ("STATE_LICENSE", "STATELICENSE"),
    ("STATE_TIN", "STATETIN"),
    ("SL_EXPIRES", "SLEXPIRES"),
    ("MEDICAID_ID", "MEDICAIDID"),
    ("MEDICAID_PROVIDER_ID", "MEDICAIDPROVIDERID"),
    ("MED_PROVIDER_ID", "MEDPROVIDERID"),
    ("NPPES_ENUM_DATE", "NPPESENUMDATE"),
    ("DEACTIVATION_CODE", "DEACTIVATIONCODE"),
    ("REINSTATEMENT_CODE", "REINSTATEMENTCODE"),
    ("REINSTATEMENT_DATE", "REINSTATEMENTDATE"),
    ("AFFILIATION_CODE", "AFFILIATIONCODE"),
    ("AFFILIATION_DATE", "AFFILIATIONDATE"),
    ("PAY_CENTER_CODE", "PAYCENTERCODE"),
    ("PAY_CENTER_DATE", "PAYCENTERDATE"),
    ("EFT_ROUTE", "EFTROUTE"),
    ("ROUTING_NUMBER", "ROUTINGNUMBER"),
    ("ACCOUNT_NUMBER", "ACCOUNTNUMBER"),
    ("CHECK_TYPE", "CHECKTYPE"),
    ("RECEIVER_ID_835", "RECEIVERID835"),
    ("NCPDP_835_DIR", "NCPDP835DIR"),
    ("REMIT_RECON_ID", "REMITRECONID"),
    ("REMIT_RECON_DATE", "REMITRECONDATE"),
    ("PAYMENT_TERM_DAYS", "PAYMENTTERMDAYS"),
    ("ADMIN_FEE", "ADMINFEE"),
    ("PRECINCT_TAX", "PRECINCTTAX"),
    ("INTERVENTION_PERC", "INTERVENTIONPERC"),
    ("IS_24_HOUR", "FLAG24HOURS"),
    ("SUN_HOURS", "SUNHOURS"),
    ("MON_HOURS", "MONHOURS"),
    ("TUE_HOURS", "TUEHOURS"),
    ("WED_HOURS", "WEDHOURS"),
    ("THU_HOURS", "THUHOURS"),
    ("FRI_HOURS", "FRIHOURS"),
    ("SAT_HOURS", "SATHOURS"),
    ("LONG_TERM_CARE_IND", "LONGTERMCAREIND"),
    ("ASSISTED_LIVING_IND", "ASSISTEDLIVINGIND"),
    ("ACCEPT_ERX_CODE", "ACCEPTERXCODE"),
    ("DELIVERY_SERVICE_CODE", "DELIVERYSERVICECODE"),
    ("COMPOUNDING_CODE", "COMPOUNDINGCODE"),
    ("DRIVE_UP_CODE", "DRIVEUPCODE"),
    ("DME_CODE", "DMECODE"),
    ("WALKIN_CLINIC_CODE", "WALKINCLINICCODE"),
    ("HH24_EMERGENCY_CODE", "HH24EMERGENCYCODE"),
    ("MULTIDOSE_PKG_CODE", "MULTIDOSEPKGCODE"),
    ("IMMUNIZATION_CODE", "IMMUNIZATIONCODE"),
    ("HANDICAP_ACCESS_CODE", "HANDICAPACCESSCODE"),
    ("STATUS_340B_CODE", "STATUS340BCODE"),
    ("CLOSED_DOOR_FACILITY_CODE", "CLOSEDDOORFACILITYCODE"),
    ("PSERVICES_OTHER", "PSERVICESOTHER"),
    ("LANG_BF", "LANGBF"),
    ("SERVICE_BF", "SERVICEBF"),
    ("SERVICE_BF2", "SERVICEBF2"),
    ("BIT_FLAGS", "BITFLAGS"),
    ("BIT_FLAGS2", "BITFLAGS2"),
    ("PRIOR_AUTH_FLAGS", "PRIORAUTHFLAGS"),
    ("ERX_NETWORK_ID", "ERXNETWORKID"),
    ("ERX_SERVICE_LEVEL_CODES", "ERXSERVICELEVELCODES"),
    ("ERX_EFFECTIVE_FROM_DATE", "ERXEFFECTIVEFROMDATE"),
    ("ERX_EFFECTIVE_THRU_DATE", "ERXEFFECTIVETHRUDATE"),
    ("OPEN_DATE", "OPENDATE"),
    ("DATE_ENTERED", "DATEENTERED"),
    ("DATE_TERMED", "DATETERMED"),
    ("DATE_CRED", "DATECRED"),
    ("RECRED_DATE", "RECREDDATE"),
    ("MOD_DATE", "MODDATE"),
    ("MOD_USER", "MODUSER"),
    ("TEST_ONLY", "TESTONLY"),
    ("NO_UPDATE", "NOUPDATE"),
    ("FILE_MEDIA", "FILEMEDIA"),
]


def upgrade() -> None:
    for old_name, new_name in _RENAMES:
        op.alter_column("pharmacies", old_name, new_column_name=new_name)
    op.drop_index("ix_pharmacies_npi", table_name="pharmacies")
    op.create_index(
        "APP_PHARMACIES_NPI_IDX", "pharmacies", ["NPI"], unique=True
    )


def downgrade() -> None:
    op.drop_index("APP_PHARMACIES_NPI_IDX", table_name="pharmacies")
    op.create_index("ix_pharmacies_npi", "pharmacies", ["NPI"], unique=False)

    for old_name, new_name in _RENAMES:
        op.alter_column("pharmacies", new_name, new_column_name=old_name)
