"""add additional pharmacy fields

Revision ID: 2d27b194a8e4
Revises: bf9bb90214b7
Create Date: 2026-08-12 15:07:33.703419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2d27b194a8e4'
down_revision: Union[str, Sequence[str], None] = 'bf9bb90214b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_existing_columns: dict[str, set[str]] = {}


def _add_column(table: str, column: sa.Column) -> None:
    """Add the column unless this database already carries it.

    A database that ran this revision while it sat on a since-deleted branch
    already has some of these columns, and adding one twice is ORA-01430. On a
    database that has none of them this behaves exactly like op.add_column.
    """
    if table not in _existing_columns:
        _existing_columns[table] = {
            c["name"] for c in sa.inspect(op.get_bind()).get_columns(table)
        }
    if column.name in _existing_columns[table]:
        return
    op.add_column(table, column)
    _existing_columns[table].add(column.name)


def upgrade() -> None:
    _add_column('pharmacies', sa.Column('pharm_name2', sa.String(length=10), nullable=True))
    _add_column('pharmacies', sa.Column('legal_name', sa.String(length=60), nullable=True))
    _add_column('pharmacies', sa.Column('doctor_name', sa.String(length=60), nullable=True))
    _add_column('pharmacies', sa.Column('address_line2', sa.String(length=55), nullable=True))
    _add_column('pharmacies', sa.Column('address_line3', sa.String(length=35), nullable=True))
    _add_column('pharmacies', sa.Column('county', sa.String(length=50), nullable=True))
    _add_column('pharmacies', sa.Column('county_fips_code', sa.String(length=5), nullable=True))
    _add_column('pharmacies', sa.Column('msa', sa.String(length=4), nullable=True))
    _add_column('pharmacies', sa.Column('pmsa', sa.String(length=4), nullable=True))
    _add_column('pharmacies', sa.Column('voting_district', sa.String(length=4), nullable=True))
    _add_column('pharmacies', sa.Column('directions', sa.String(length=50), nullable=True))
    _add_column('pharmacies', sa.Column('latitude', sa.Numeric(), nullable=True))
    _add_column('pharmacies', sa.Column('longitude', sa.Numeric(), nullable=True))
    _add_column('pharmacies', sa.Column('mail_addr1', sa.String(length=55), nullable=True))
    _add_column('pharmacies', sa.Column('mail_addr2', sa.String(length=55), nullable=True))
    _add_column('pharmacies', sa.Column('mail_city', sa.String(length=35), nullable=True))
    _add_column('pharmacies', sa.Column('mail_state', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('mail_zip', sa.String(length=11), nullable=True))
    _add_column('pharmacies', sa.Column('phone_ext', sa.String(length=5), nullable=True))
    _add_column('pharmacies', sa.Column('email', sa.String(length=100), nullable=True))
    _add_column('pharmacies', sa.Column('pharm_email', sa.String(length=50), nullable=True))
    _add_column('pharmacies', sa.Column('website', sa.String(length=50), nullable=True))
    _add_column('pharmacies', sa.Column('hospice_phone', sa.String(length=10), nullable=True))
    _add_column('pharmacies', sa.Column('hospice_fax', sa.String(length=10), nullable=True))
    _add_column('pharmacies', sa.Column('contact_first_name', sa.String(length=20), nullable=True))
    _add_column('pharmacies', sa.Column('contact_last_name', sa.String(length=20), nullable=True))
    _add_column('pharmacies', sa.Column('contact_mi', sa.String(length=1), nullable=True))
    _add_column('pharmacies', sa.Column('contact_title', sa.String(length=30), nullable=True))
    _add_column('pharmacies', sa.Column('contact_phone', sa.String(length=10), nullable=True))
    _add_column('pharmacies', sa.Column('contact_phone_ext', sa.String(length=5), nullable=True))
    _add_column('pharmacies', sa.Column('contact_email', sa.String(length=50), nullable=True))
    _add_column('pharmacies', sa.Column('disp_class', sa.String(length=3), nullable=True))
    _add_column('pharmacies', sa.Column('disp_type', sa.String(length=3), nullable=True))
    _add_column('pharmacies', sa.Column('disp_type2', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('disp_type3', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('dir_name', sa.String(length=50), nullable=True))
    _add_column('pharmacies', sa.Column('dir_chain', sa.String(length=50), nullable=True))
    _add_column('pharmacies', sa.Column('dir_class', sa.String(length=50), nullable=True))
    _add_column('pharmacies', sa.Column('jurisdiction', sa.String(length=10), nullable=True))
    _add_column('pharmacies', sa.Column('fed_licence', sa.String(length=12), nullable=True))
    _add_column('pharmacies', sa.Column('fed_tin', sa.String(length=15), nullable=True))
    _add_column('pharmacies', sa.Column('fed_expiration_date', sa.Date(), nullable=True))
    _add_column('pharmacies', sa.Column('state_licence', sa.String(length=20), nullable=True))
    _add_column('pharmacies', sa.Column('state_license', sa.String(length=20), nullable=True))
    _add_column('pharmacies', sa.Column('state_tin', sa.String(length=15), nullable=True))
    _add_column('pharmacies', sa.Column('sl_expires', sa.Date(), nullable=True))
    _add_column('pharmacies', sa.Column('medicaid_id', sa.String(length=20), nullable=True))
    _add_column('pharmacies', sa.Column('medicaid_provider_id', sa.String(length=35), nullable=True))
    _add_column('pharmacies', sa.Column('med_provider_id', sa.String(length=20), nullable=True))
    _add_column('pharmacies', sa.Column('dea', sa.String(length=12), nullable=True))
    _add_column('pharmacies', sa.Column('nppes_enum_date', sa.Date(), nullable=True))
    _add_column('pharmacies', sa.Column('deactivation_code', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('reinstatement_code', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('reinstatement_date', sa.Date(), nullable=True))
    _add_column('pharmacies', sa.Column('affiliation_code', sa.String(length=3), nullable=True))
    _add_column('pharmacies', sa.Column('affiliation_date', sa.Date(), nullable=True))
    _add_column('pharmacies', sa.Column('pay_center_code', sa.String(length=7), nullable=True))
    _add_column('pharmacies', sa.Column('pay_center_date', sa.Date(), nullable=True))
    _add_column('pharmacies', sa.Column('eft_route', sa.String(length=9), nullable=True))
    _add_column('pharmacies', sa.Column('routing_number', sa.String(length=20), nullable=True))
    _add_column('pharmacies', sa.Column('account_number', sa.String(length=20), nullable=True))
    _add_column('pharmacies', sa.Column('ach', sa.String(length=1), nullable=True))
    _add_column('pharmacies', sa.Column('check_type', sa.String(length=10), nullable=True))
    _add_column('pharmacies', sa.Column('receiver_id_835', sa.String(length=15), nullable=True))
    _add_column('pharmacies', sa.Column('ncpdp_835_dir', sa.String(length=50), nullable=True))
    _add_column('pharmacies', sa.Column('remit_recon_id', sa.String(length=6), nullable=True))
    _add_column('pharmacies', sa.Column('remit_recon_date', sa.Date(), nullable=True))
    _add_column('pharmacies', sa.Column('payment_term_days', sa.Integer(), nullable=True))
    _add_column('pharmacies', sa.Column('admin_fee', sa.Numeric(), nullable=True))
    _add_column('pharmacies', sa.Column('precinct_tax', sa.Numeric(), nullable=True))
    _add_column('pharmacies', sa.Column('intervention_perc', sa.Numeric(), nullable=True))
    _add_column('pharmacies', sa.Column('contracted', sa.String(length=1), nullable=True))
    _add_column('pharmacies', sa.Column('sun_hours', sa.String(length=5), nullable=True))
    _add_column('pharmacies', sa.Column('mon_hours', sa.String(length=5), nullable=True))
    _add_column('pharmacies', sa.Column('tue_hours', sa.String(length=5), nullable=True))
    _add_column('pharmacies', sa.Column('wed_hours', sa.String(length=5), nullable=True))
    _add_column('pharmacies', sa.Column('thu_hours', sa.String(length=5), nullable=True))
    _add_column('pharmacies', sa.Column('fri_hours', sa.String(length=5), nullable=True))
    _add_column('pharmacies', sa.Column('sat_hours', sa.String(length=5), nullable=True))
    _add_column('pharmacies', sa.Column('long_term_care_ind', sa.String(length=1), nullable=True))
    _add_column('pharmacies', sa.Column('assisted_living_ind', sa.String(length=1), nullable=True))
    _add_column('pharmacies', sa.Column('accept_erx_code', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('delivery_service_code', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('compounding_code', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('drive_up_code', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('dme_code', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('walkin_clinic_code', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('hh24_emergency_code', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('multidose_pkg_code', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('immunization_code', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('handicap_access_code', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('status_340b_code', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('closed_door_facility_code', sa.String(length=2), nullable=True))
    _add_column('pharmacies', sa.Column('pservices_other', sa.String(length=25), nullable=True))
    _add_column('pharmacies', sa.Column('lang_bf', sa.Integer(), nullable=True))
    _add_column('pharmacies', sa.Column('service_bf', sa.Integer(), nullable=True))
    _add_column('pharmacies', sa.Column('service_bf2', sa.Integer(), nullable=True))
    _add_column('pharmacies', sa.Column('bit_flags', sa.Integer(), nullable=True))
    _add_column('pharmacies', sa.Column('bit_flags2', sa.Integer(), nullable=True))
    _add_column('pharmacies', sa.Column('prior_auth_flags', sa.Integer(), nullable=True))
    _add_column('pharmacies', sa.Column('erx_network_id', sa.String(length=3), nullable=True))
    _add_column('pharmacies', sa.Column('erx_service_level_codes', sa.String(length=100), nullable=True))
    _add_column('pharmacies', sa.Column('erx_effective_from_date', sa.Date(), nullable=True))
    _add_column('pharmacies', sa.Column('erx_effective_thru_date', sa.Date(), nullable=True))
    _add_column('pharmacies', sa.Column('open_date', sa.Date(), nullable=True))
    _add_column('pharmacies', sa.Column('date_entered', sa.Date(), nullable=True))
    _add_column('pharmacies', sa.Column('date_termed', sa.Date(), nullable=True))
    _add_column('pharmacies', sa.Column('date_cred', sa.Date(), nullable=True))
    _add_column('pharmacies', sa.Column('recred_date', sa.Date(), nullable=True))
    _add_column('pharmacies', sa.Column('mod_date', sa.Date(), nullable=True))
    _add_column('pharmacies', sa.Column('mod_user', sa.String(length=20), nullable=True))
    _add_column('pharmacies', sa.Column('test_only', sa.Boolean(), nullable=True))
    _add_column('pharmacies', sa.Column('no_update', sa.String(length=1), nullable=True))
    _add_column('pharmacies', sa.Column('file_media', sa.String(length=10), nullable=True))


def downgrade() -> None:
    op.drop_column('pharmacies', 'file_media')
    op.drop_column('pharmacies', 'no_update')
    op.drop_column('pharmacies', 'test_only')
    op.drop_column('pharmacies', 'mod_user')
    op.drop_column('pharmacies', 'mod_date')
    op.drop_column('pharmacies', 'recred_date')
    op.drop_column('pharmacies', 'date_cred')
    op.drop_column('pharmacies', 'date_termed')
    op.drop_column('pharmacies', 'date_entered')
    op.drop_column('pharmacies', 'open_date')
    op.drop_column('pharmacies', 'erx_effective_thru_date')
    op.drop_column('pharmacies', 'erx_effective_from_date')
    op.drop_column('pharmacies', 'erx_service_level_codes')
    op.drop_column('pharmacies', 'erx_network_id')
    op.drop_column('pharmacies', 'prior_auth_flags')
    op.drop_column('pharmacies', 'bit_flags2')
    op.drop_column('pharmacies', 'bit_flags')
    op.drop_column('pharmacies', 'service_bf2')
    op.drop_column('pharmacies', 'service_bf')
    op.drop_column('pharmacies', 'lang_bf')
    op.drop_column('pharmacies', 'pservices_other')
    op.drop_column('pharmacies', 'closed_door_facility_code')
    op.drop_column('pharmacies', 'status_340b_code')
    op.drop_column('pharmacies', 'handicap_access_code')
    op.drop_column('pharmacies', 'immunization_code')
    op.drop_column('pharmacies', 'multidose_pkg_code')
    op.drop_column('pharmacies', 'hh24_emergency_code')
    op.drop_column('pharmacies', 'walkin_clinic_code')
    op.drop_column('pharmacies', 'dme_code')
    op.drop_column('pharmacies', 'drive_up_code')
    op.drop_column('pharmacies', 'compounding_code')
    op.drop_column('pharmacies', 'delivery_service_code')
    op.drop_column('pharmacies', 'accept_erx_code')
    op.drop_column('pharmacies', 'assisted_living_ind')
    op.drop_column('pharmacies', 'long_term_care_ind')
    op.drop_column('pharmacies', 'sat_hours')
    op.drop_column('pharmacies', 'fri_hours')
    op.drop_column('pharmacies', 'thu_hours')
    op.drop_column('pharmacies', 'wed_hours')
    op.drop_column('pharmacies', 'tue_hours')
    op.drop_column('pharmacies', 'mon_hours')
    op.drop_column('pharmacies', 'sun_hours')
    op.drop_column('pharmacies', 'contracted')
    op.drop_column('pharmacies', 'intervention_perc')
    op.drop_column('pharmacies', 'precinct_tax')
    op.drop_column('pharmacies', 'admin_fee')
    op.drop_column('pharmacies', 'payment_term_days')
    op.drop_column('pharmacies', 'remit_recon_date')
    op.drop_column('pharmacies', 'remit_recon_id')
    op.drop_column('pharmacies', 'ncpdp_835_dir')
    op.drop_column('pharmacies', 'receiver_id_835')
    op.drop_column('pharmacies', 'check_type')
    op.drop_column('pharmacies', 'ach')
    op.drop_column('pharmacies', 'account_number')
    op.drop_column('pharmacies', 'routing_number')
    op.drop_column('pharmacies', 'eft_route')
    op.drop_column('pharmacies', 'pay_center_date')
    op.drop_column('pharmacies', 'pay_center_code')
    op.drop_column('pharmacies', 'affiliation_date')
    op.drop_column('pharmacies', 'affiliation_code')
    op.drop_column('pharmacies', 'reinstatement_date')
    op.drop_column('pharmacies', 'reinstatement_code')
    op.drop_column('pharmacies', 'deactivation_code')
    op.drop_column('pharmacies', 'nppes_enum_date')
    op.drop_column('pharmacies', 'dea')
    op.drop_column('pharmacies', 'med_provider_id')
    op.drop_column('pharmacies', 'medicaid_provider_id')
    op.drop_column('pharmacies', 'medicaid_id')
    op.drop_column('pharmacies', 'sl_expires')
    op.drop_column('pharmacies', 'state_tin')
    op.drop_column('pharmacies', 'state_license')
    op.drop_column('pharmacies', 'state_licence')
    op.drop_column('pharmacies', 'fed_expiration_date')
    op.drop_column('pharmacies', 'fed_tin')
    op.drop_column('pharmacies', 'fed_licence')
    op.drop_column('pharmacies', 'jurisdiction')
    op.drop_column('pharmacies', 'dir_class')
    op.drop_column('pharmacies', 'dir_chain')
    op.drop_column('pharmacies', 'dir_name')
    op.drop_column('pharmacies', 'disp_type3')
    op.drop_column('pharmacies', 'disp_type2')
    op.drop_column('pharmacies', 'disp_type')
    op.drop_column('pharmacies', 'disp_class')
    op.drop_column('pharmacies', 'contact_email')
    op.drop_column('pharmacies', 'contact_phone_ext')
    op.drop_column('pharmacies', 'contact_phone')
    op.drop_column('pharmacies', 'contact_title')
    op.drop_column('pharmacies', 'contact_mi')
    op.drop_column('pharmacies', 'contact_last_name')
    op.drop_column('pharmacies', 'contact_first_name')
    op.drop_column('pharmacies', 'hospice_fax')
    op.drop_column('pharmacies', 'hospice_phone')
    op.drop_column('pharmacies', 'website')
    op.drop_column('pharmacies', 'pharm_email')
    op.drop_column('pharmacies', 'email')
    op.drop_column('pharmacies', 'phone_ext')
    op.drop_column('pharmacies', 'mail_zip')
    op.drop_column('pharmacies', 'mail_state')
    op.drop_column('pharmacies', 'mail_city')
    op.drop_column('pharmacies', 'mail_addr2')
    op.drop_column('pharmacies', 'mail_addr1')
    op.drop_column('pharmacies', 'longitude')
    op.drop_column('pharmacies', 'latitude')
    op.drop_column('pharmacies', 'directions')
    op.drop_column('pharmacies', 'voting_district')
    op.drop_column('pharmacies', 'pmsa')
    op.drop_column('pharmacies', 'msa')
    op.drop_column('pharmacies', 'county_fips_code')
    op.drop_column('pharmacies', 'county')
    op.drop_column('pharmacies', 'address_line3')
    op.drop_column('pharmacies', 'address_line2')
    op.drop_column('pharmacies', 'doctor_name')
    op.drop_column('pharmacies', 'legal_name')
    op.drop_column('pharmacies', 'pharm_name2')
