"""claim-search table

Revision ID: 5c7576d2f719
Revises: 0a3054329f6f
Create Date: 2026-06-19 05:59:23.020338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5c7576d2f719'
down_revision: Union[str, Sequence[str], None] = '0a3054329f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('auth_num', sa.String(length=20), nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('rx_number', sa.String(length=20), nullable=False),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('ndc', sa.String(length=13), nullable=False),
    sa.Column('date_filled', sa.Date(), nullable=False),
    sa.Column('date_written', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('days_supply', sa.Integer(), nullable=True),
    sa.Column('refills_remaining', sa.Integer(), nullable=True),
    sa.Column('pharmacy_npi', sa.String(length=10), nullable=True),
    sa.Column('pharmacy_name', sa.String(length=255), nullable=True),
    sa.Column('prescriber_npi', sa.String(length=10), nullable=True),
    sa.Column('prescriber_name', sa.String(length=255), nullable=True),
    sa.Column('ingredient_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dispensing_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('copay', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_test_claim', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('plan_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id']),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_auth_num'), 'claims', ['auth_num'], unique=True)
    op.create_index(op.f('ix_claims_claim_id'), 'claims', ['claim_id'], unique=True)
    op.create_index(op.f('ix_claims_date_filled'), 'claims', ['date_filled'], unique=False)
    op.create_index(op.f('ix_claims_member_id'), 'claims', ['member_id'], unique=False)
    op.create_index('ix_claims_member_id_date_filled_is_test_claim', 'claims', ['member_id', 'date_filled', 'is_test_claim'], unique=False)
    op.create_index(op.f('ix_claims_ndc'), 'claims', ['ndc'], unique=False)
    op.create_index(op.f('ix_claims_rx_number'), 'claims', ['rx_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_rx_number'), table_name='claims')
    op.drop_index(op.f('ix_claims_ndc'), table_name='claims')
    op.drop_index('ix_claims_member_id_date_filled_is_test_claim', table_name='claims')
    op.drop_index(op.f('ix_claims_member_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_date_filled'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_auth_num'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
