import uuid
from datetime import date, datetime
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "a5b6c7d8e9f0"
down_revision: Union[str, Sequence[str], None] = "f4a5b6c7d8e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_prior_auths = sa.table(
    "prior_auths",
    sa.column("id", sa.Uuid(as_uuid=True)),
    sa.column("authnum", sa.Numeric()),
    sa.column("subscribernum", sa.String(45)),
    sa.column("groupnum", sa.String(20)),
    sa.column("personcodes", sa.String(50)),
    sa.column("effdate", sa.Date()),
    sa.column("termdate", sa.Date()),
    sa.column("providerid", sa.String(30)),
    sa.column("prescriberid", sa.String(15)),
    sa.column("ndc", sa.String(11)),
    sa.column("gpi", sa.String(14)),
    sa.column("bg", sa.String(1)),
    sa.column("action", sa.String(1)),
    sa.column("genname", sa.String(60)),
    sa.column("deaclass", sa.String(9)),
    sa.column("refills", sa.String(4)),
    sa.column("maxdailydose", sa.String(5)),
    sa.column("maxscriptqty", sa.String(10)),
    sa.column("maxscriptdays", sa.String(5)),
    sa.column("maxscripts", sa.Numeric()),
    sa.column("createuser", sa.String(20)),
    sa.column("createts", sa.DateTime()),
    sa.column("changeuser", sa.String(20)),
    sa.column("changets", sa.DateTime()),
    sa.column("reasoncode", sa.String(20)),
    sa.column("notes", sa.String(4000)),
    sa.column("message", sa.String(100)),
    sa.column("source", sa.String(10)),
    sa.column("authby", sa.String(50)),
    sa.column("calledinby", sa.String(50)),
    sa.column("quickcode", sa.String(10)),
    sa.column("appeal", sa.String(3)),
    sa.column("denial", sa.String(2)),
    sa.column("timeframe", sa.String(2)),
    sa.column("reqreceived", sa.Date()),
    sa.column("documentation", sa.Date()),
    sa.column("reqapproved", sa.Date()),
    sa.column("memnotified", sa.Date()),
    sa.column("daysold", sa.Numeric()),
    sa.column("diagnosis", sa.String(100)),
    sa.column("mpatype", sa.String(25)),
    sa.column("brand", sa.String(4)),
    sa.column("reportingtype", sa.String(15)),
    sa.column("basic_review_date", sa.Date()),
    sa.column("standard_review_date", sa.Date()),
)

_SEED: tuple[dict, ...] = (
    {
        "authnum": 1001,
        "subscribernum": "INS001",
        "groupnum": "GRP001",
        "personcodes": "01",
        "effdate": date(2025, 1, 1),
        "termdate": date(2025, 12, 31),
        "providerid": "2400214",
        "prescriberid": "1326367012",
        "ndc": "00074580302",
        "gpi": "66000015100315",
        "bg": "B",
        "action": "A",
        "genname": "ADALIMUMAB",
        "brand": "HUMI",
        "refills": "11",
        "maxdailydose": "0.06",
        "maxscriptqty": "2",
        "maxscriptdays": "28",
        "maxscripts": 13,
        "createuser": "admin",
        "createts": datetime(2024, 12, 18, 9, 14, 0),
        "reasoncode": "SPECIALTY",
        "notes": "Specialty PA approved for RA. Step therapy with methotrexate documented.",
        "message": "PA APPROVED - SPECIALTY PHARMACY REQUIRED",
        "source": "WEB",
        "authby": "DR. ANITA PATEL",
        "calledinby": "RHEUM CLINIC INTAKE",
        "quickcode": "SPEC01",
        "appeal": "N",
        "reqreceived": date(2024, 12, 15),
        "documentation": date(2024, 12, 17),
        "reqapproved": date(2024, 12, 18),
        "memnotified": date(2024, 12, 19),
        "daysold": 3,
        "diagnosis": "M06.9 RHEUMATOID ARTHRITIS UNSPECIFIED",
        "mpatype": "SPECIALTY",
        "reportingtype": "STANDARD",
        "standard_review_date": date(2024, 12, 18),
    },
    {
        "authnum": 1002,
        "subscribernum": "INS001",
        "groupnum": "GRP001",
        "personcodes": "02",
        "effdate": date(2025, 3, 1),
        "termdate": date(2026, 2, 28),
        "providerid": "1510388",
        "prescriberid": "1548930214",
        "ndc": "00093108256",
        "gpi": "27600030010320",
        "bg": "G",
        "action": "A",
        "genname": "METFORMIN HCL",
        "refills": "11",
        "maxscriptqty": "180",
        "maxscriptdays": "90",
        "maxscripts": 4,
        "createuser": "user",
        "createts": datetime(2025, 2, 24, 11, 2, 0),
        "reasoncode": "QTY LIMIT",
        "notes": "Quantity limit override to 180 tabs per 90 day fill.",
        "message": "PA APPROVED - QUANTITY LIMIT OVERRIDE",
        "source": "WEB",
        "authby": "DR. SUSAN KIM",
        "quickcode": "QTY01",
        "appeal": "N",
        "reqreceived": date(2025, 2, 21),
        "reqapproved": date(2025, 2, 24),
        "memnotified": date(2025, 2, 25),
        "daysold": 3,
        "diagnosis": "E11.9 TYPE 2 DIABETES MELLITUS WITHOUT COMPLICATIONS",
        "mpatype": "STANDARD",
        "reportingtype": "STANDARD",
        "basic_review_date": date(2025, 2, 24),
    },
    {
        "authnum": 1003,
        "subscribernum": "INS002",
        "groupnum": "GRP002",
        "personcodes": "01",
        "effdate": date(2025, 5, 1),
        "termdate": date(2026, 4, 30),
        "providerid": "3608812",
        "prescriberid": "1548930214",
        "ndc": "00088502005",
        "gpi": "27100010100330",
        "bg": "B",
        "action": "A",
        "genname": "INSULIN GLARGINE",
        "brand": "LANT",
        "refills": "11",
        "maxscriptqty": "15",
        "maxscriptdays": "30",
        "maxscripts": 12,
        "createuser": "admin",
        "createts": datetime(2025, 4, 25, 15, 41, 0),
        "reasoncode": "NON FORM",
        "notes": "Non-formulary brand approved; member intolerant to formulary alternative.",
        "message": "PA APPROVED - NON FORMULARY EXCEPTION",
        "source": "FAX",
        "authby": "DR. SUSAN KIM",
        "calledinby": "ENDO CLINIC",
        "quickcode": "NF01",
        "appeal": "N",
        "reqreceived": date(2025, 4, 22),
        "documentation": date(2025, 4, 24),
        "reqapproved": date(2025, 4, 25),
        "memnotified": date(2025, 4, 26),
        "daysold": 3,
        "diagnosis": "E10.9 TYPE 1 DIABETES MELLITUS WITHOUT COMPLICATIONS",
        "mpatype": "STANDARD",
        "reportingtype": "STANDARD",
        "standard_review_date": date(2025, 4, 25),
    },
    {
        "authnum": 1004,
        "subscribernum": "INS002",
        "groupnum": "GRP002",
        "personcodes": "02",
        "effdate": date(2025, 6, 1),
        "termdate": date(2025, 6, 1),
        "providerid": "2719045",
        "prescriberid": "1437821903",
        "ndc": "00074580302",
        "gpi": "66000015100315",
        "bg": "B",
        "action": "D",
        "genname": "ADALIMUMAB",
        "brand": "HUMI",
        "createuser": "admin",
        "createts": datetime(2025, 6, 1, 8, 30, 0),
        "changeuser": "admin",
        "changets": datetime(2025, 6, 9, 16, 5, 0),
        "reasoncode": "STEP THER",
        "notes": "Denied: step therapy requirement not met, no trial of preferred agent on file.",
        "message": "PA DENIED - STEP THERAPY NOT MET",
        "source": "PHONE",
        "authby": "CLINICAL REVIEW",
        "calledinby": "DR BENNETT OFFICE",
        "appeal": "Y",
        "denial": "03",
        "timeframe": "72",
        "reqreceived": date(2025, 5, 29),
        "documentation": date(2025, 5, 30),
        "memnotified": date(2025, 6, 2),
        "daysold": 3,
        "diagnosis": "L40.0 PSORIASIS VULGARIS",
        "mpatype": "SPECIALTY",
        "reportingtype": "EXPEDITED",
        "standard_review_date": date(2025, 6, 1),
    },
    {
        "authnum": 1005,
        "subscribernum": "INS003",
        "groupnum": "GRP003",
        "personcodes": "01",
        "effdate": date(2025, 7, 1),
        "termdate": date(2026, 6, 30),
        "providerid": "2400214",
        "prescriberid": "1659041325",
        "ndc": "00173068220",
        "gpi": "44200010206920",
        "bg": "B",
        "action": "A",
        "genname": "ALBUTEROL SULFATE",
        "brand": "VENT",
        "refills": "5",
        "maxscriptqty": "2",
        "maxscriptdays": "30",
        "maxscripts": 6,
        "createuser": "user",
        "createts": datetime(2025, 6, 26, 10, 12, 0),
        "reasoncode": "QTY LIMIT",
        "notes": "Two inhalers per 30 days approved for exercise induced asthma.",
        "message": "PA APPROVED - QUANTITY LIMIT OVERRIDE",
        "source": "WEB",
        "authby": "DR. MICHAEL OBRIEN",
        "quickcode": "QTY01",
        "appeal": "N",
        "reqreceived": date(2025, 6, 24),
        "reqapproved": date(2025, 6, 26),
        "memnotified": date(2025, 6, 27),
        "daysold": 2,
        "diagnosis": "J45.909 UNSPECIFIED ASTHMA UNCOMPLICATED",
        "mpatype": "STANDARD",
        "reportingtype": "STANDARD",
        "basic_review_date": date(2025, 6, 26),
    },
    {
        "authnum": 1006,
        "subscribernum": "INS001",
        "groupnum": "GRP001",
        "personcodes": "01,02",
        "effdate": date(2024, 2, 1),
        "termdate": date(2024, 7, 31),
        "providerid": "1510388",
        "prescriberid": "1437821903",
        "ndc": "00406012405",
        "gpi": "65991002100310",
        "bg": "G",
        "action": "A",
        "genname": "HYDROCODONE/APAP",
        "deaclass": "CII",
        "refills": "0",
        "maxdailydose": "6",
        "maxscriptqty": "60",
        "maxscriptdays": "10",
        "maxscripts": 1,
        "createuser": "admin",
        "createts": datetime(2024, 1, 29, 13, 55, 0),
        "changeuser": "admin",
        "changets": datetime(2024, 8, 1, 7, 0, 0),
        "reasoncode": "ACUTE",
        "notes": "Short term post surgical PA. Expired, retained for history.",
        "message": "PA EXPIRED",
        "source": "PHONE",
        "authby": "DR. JAMES BENNETT",
        "quickcode": "ACUTE1",
        "appeal": "N",
        "reqreceived": date(2024, 1, 26),
        "documentation": date(2024, 1, 28),
        "reqapproved": date(2024, 1, 29),
        "memnotified": date(2024, 1, 30),
        "daysold": 3,
        "diagnosis": "Z98.890 OTHER SPECIFIED POSTPROCEDURAL STATES",
        "mpatype": "STANDARD",
        "reportingtype": "STANDARD",
        "basic_review_date": date(2024, 1, 29),
    },
    {
        "authnum": 1007,
        "subscribernum": "INS003",
        "groupnum": "GRP003",
        "personcodes": "01",
        "effdate": date(2026, 2, 1),
        "termdate": date(2027, 1, 31),
        "providerid": "0512367",
        "prescriberid": "1871263547",
        "ndc": "00185006601",
        "gpi": "58160040100310",
        "bg": "G",
        "action": "A",
        "genname": "SERTRALINE HCL",
        "refills": "11",
        "maxdailydose": "100",
        "maxscriptqty": "90",
        "maxscriptdays": "90",
        "maxscripts": 4,
        "createuser": "user",
        "createts": datetime(2026, 1, 27, 9, 48, 0),
        "reasoncode": "QTY LIMIT",
        "notes": "90 day supply approved for maintenance therapy, dose stable 12 months.",
        "message": "PA APPROVED - QUANTITY LIMIT OVERRIDE",
        "source": "WEB",
        "authby": "DR. DANIEL GARCIA",
        "quickcode": "QTY01",
        "appeal": "N",
        "reqreceived": date(2026, 1, 24),
        "reqapproved": date(2026, 1, 27),
        "memnotified": date(2026, 1, 28),
        "daysold": 3,
        "diagnosis": "F33.1 MAJOR DEPRESSIVE DISORDER RECURRENT MODERATE",
        "mpatype": "STANDARD",
        "reportingtype": "STANDARD",
        "basic_review_date": date(2026, 1, 27),
    },
    {
        "authnum": 1008,
        "subscribernum": "INS001",
        "groupnum": "GRP001",
        "personcodes": "03",
        "effdate": date(2026, 9, 1),
        "termdate": date(2027, 8, 31),
        "providerid": "5402891",
        "prescriberid": "1982374658",
        "ndc": "00006071154",
        "gpi": "44600020100320",
        "bg": "B",
        "genname": "MONTELUKAST SODIUM",
        "brand": "SING",
        "refills": "11",
        "maxscriptqty": "30",
        "maxscriptdays": "30",
        "maxscripts": 12,
        "createuser": "user",
        "createts": datetime(2026, 8, 5, 14, 22, 0),
        "reasoncode": "NON FORM",
        "notes": "Awaiting chart notes for non-preferred brand request. Pending review.",
        "message": "PA PENDING - CLINICAL REVIEW",
        "source": "WEB",
        "calledinby": "PEDS CLINIC INTAKE",
        "appeal": "N",
        "reqreceived": date(2026, 8, 5),
        "daysold": 5,
        "diagnosis": "J45.909 UNSPECIFIED ASTHMA UNCOMPLICATED",
        "mpatype": "STANDARD",
        "reportingtype": "STANDARD",
    },
    {
        "authnum": 1009,
        "subscribernum": "INS013",
        "groupnum": "GRP002",
        "personcodes": "01",
        "effdate": date(2026, 3, 1),
        "termdate": date(2027, 2, 28),
        "providerid": "1133402",
        "prescriberid": "1437829103",
        "ndc": "00378512093",
        "gpi": "49270060000320",
        "bg": "G",
        "action": "A",
        "genname": "OMEPRAZOLE DR",
        "refills": "5",
        "maxdailydose": "40",
        "maxscriptqty": "60",
        "maxscriptdays": "30",
        "maxscripts": 6,
        "createuser": "admin",
        "createts": datetime(2026, 2, 24, 10, 5, 0),
        "reasoncode": "QTY LIMIT",
        "notes": "BID dosing approved for erosive esophagitis confirmed on endoscopy.",
        "message": "PA APPROVED - QUANTITY LIMIT OVERRIDE",
        "source": "FAX",
        "authby": "DR. STEVEN LEE",
        "calledinby": "GI CLINIC",
        "quickcode": "QTY01",
        "appeal": "N",
        "reqreceived": date(2026, 2, 20),
        "documentation": date(2026, 2, 23),
        "reqapproved": date(2026, 2, 24),
        "memnotified": date(2026, 2, 25),
        "daysold": 4,
        "diagnosis": "K21.00 GERD WITH ESOPHAGITIS WITHOUT BLEEDING",
        "mpatype": "STANDARD",
        "reportingtype": "STANDARD",
        "basic_review_date": date(2026, 2, 24),
    },
    {
        "authnum": 1010,
        "subscribernum": "INS014",
        "groupnum": "GRP003",
        "personcodes": "01",
        "effdate": date(2026, 4, 1),
        "termdate": date(2027, 3, 31),
        "providerid": "4901223",
        "prescriberid": "1326718092",
        "ndc": "00074580302",
        "gpi": "66000015100315",
        "bg": "B",
        "action": "A",
        "genname": "ADALIMUMAB",
        "brand": "HUMI",
        "refills": "11",
        "maxdailydose": "0.06",
        "maxscriptqty": "2",
        "maxscriptdays": "28",
        "maxscripts": 13,
        "createuser": "admin",
        "createts": datetime(2026, 3, 26, 16, 30, 0),
        "reasoncode": "SPECIALTY",
        "notes": "Specialty PA for plaque psoriasis. Topical and phototherapy trials documented.",
        "message": "PA APPROVED - SPECIALTY PHARMACY REQUIRED",
        "source": "FAX",
        "authby": "DR. MARIA RODRIGUEZ",
        "calledinby": "DERM CLINIC INTAKE",
        "quickcode": "SPEC01",
        "appeal": "N",
        "reqreceived": date(2026, 3, 20),
        "documentation": date(2026, 3, 25),
        "reqapproved": date(2026, 3, 26),
        "memnotified": date(2026, 3, 27),
        "daysold": 6,
        "diagnosis": "L40.0 PSORIASIS VULGARIS",
        "mpatype": "SPECIALTY",
        "reportingtype": "STANDARD",
        "standard_review_date": date(2026, 3, 26),
    },
    {
        "authnum": 1011,
        "subscribernum": "INS015",
        "groupnum": "GRP001",
        "personcodes": "01",
        "effdate": date(2026, 1, 15),
        "termdate": date(2026, 12, 31),
        "providerid": "3608812",
        "prescriberid": "1548930214",
        "ndc": "00088502005",
        "gpi": "27100010100330",
        "bg": "B",
        "action": "A",
        "genname": "INSULIN GLARGINE",
        "brand": "LANT",
        "refills": "11",
        "maxscriptqty": "15",
        "maxscriptdays": "30",
        "maxscripts": 12,
        "createuser": "admin",
        "createts": datetime(2026, 1, 12, 8, 55, 0),
        "reasoncode": "NON FORM",
        "notes": "Brand continued; member stabilized on current basal insulin.",
        "message": "PA APPROVED - NON FORMULARY EXCEPTION",
        "source": "WEB",
        "authby": "DR. SUSAN KIM",
        "quickcode": "NF01",
        "appeal": "N",
        "reqreceived": date(2026, 1, 9),
        "documentation": date(2026, 1, 11),
        "reqapproved": date(2026, 1, 12),
        "memnotified": date(2026, 1, 13),
        "daysold": 3,
        "diagnosis": "E11.65 TYPE 2 DIABETES MELLITUS WITH HYPERGLYCEMIA",
        "mpatype": "STANDARD",
        "reportingtype": "STANDARD",
        "standard_review_date": date(2026, 1, 12),
    },
    {
        "authnum": 1012,
        "subscribernum": "INS016",
        "groupnum": "GRP002",
        "personcodes": "01",
        "effdate": date(2026, 8, 15),
        "termdate": date(2027, 8, 14),
        "providerid": "2208934",
        "prescriberid": "1215607981",
        "ndc": "00115129701",
        "gpi": "72600030000320",
        "bg": "G",
        "genname": "GABAPENTIN",
        "refills": "5",
        "maxdailydose": "3600",
        "maxscriptqty": "360",
        "maxscriptdays": "30",
        "maxscripts": 12,
        "createuser": "user",
        "createts": datetime(2026, 7, 28, 11, 40, 0),
        "changeuser": "user",
        "changets": datetime(2026, 8, 3, 9, 15, 0),
        "reasoncode": "QTY LIMIT",
        "notes": "Documentation received 08/03; titration schedule under clinical review.",
        "message": "PA PENDING - CLINICAL REVIEW",
        "source": "PHONE",
        "calledinby": "NEURO CLINIC",
        "appeal": "N",
        "reqreceived": date(2026, 7, 28),
        "documentation": date(2026, 8, 3),
        "daysold": 13,
        "diagnosis": "G62.9 POLYNEUROPATHY UNSPECIFIED",
        "mpatype": "STANDARD",
        "reportingtype": "STANDARD",
    },
    {
        "authnum": 1013,
        "subscribernum": "INS017",
        "groupnum": "GRP003",
        "personcodes": "01",
        "effdate": date(2026, 5, 10),
        "termdate": date(2026, 5, 10),
        "providerid": "1900467",
        "prescriberid": "1437821903",
        "ndc": "00406012405",
        "gpi": "65991002100310",
        "bg": "G",
        "action": "D",
        "genname": "HYDROCODONE/APAP",
        "deaclass": "CII",
        "createuser": "admin",
        "createts": datetime(2026, 5, 10, 13, 20, 0),
        "changeuser": "admin",
        "changets": datetime(2026, 5, 14, 10, 45, 0),
        "reasoncode": "DUR",
        "notes": "Denied: exceeds MME threshold, concurrent benzodiazepine therapy on file.",
        "message": "PA DENIED - SAFETY EDIT MME LIMIT",
        "source": "PHONE",
        "authby": "CLINICAL REVIEW",
        "calledinby": "DR BENNETT OFFICE",
        "appeal": "Y",
        "denial": "07",
        "timeframe": "72",
        "reqreceived": date(2026, 5, 8),
        "documentation": date(2026, 5, 9),
        "memnotified": date(2026, 5, 12),
        "daysold": 4,
        "diagnosis": "M54.5 LOW BACK PAIN",
        "mpatype": "STANDARD",
        "reportingtype": "EXPEDITED",
        "standard_review_date": date(2026, 5, 12),
    },
    {
        "authnum": 1014,
        "subscribernum": "INS018",
        "groupnum": "GRP001",
        "personcodes": "01",
        "effdate": date(2026, 5, 1),
        "termdate": date(2027, 4, 30),
        "providerid": "3311756",
        "prescriberid": "1093485769",
        "ndc": "00173068220",
        "gpi": "44200010206920",
        "bg": "B",
        "action": "A",
        "genname": "ALBUTEROL SULFATE",
        "brand": "VENT",
        "refills": "11",
        "maxscriptqty": "3",
        "maxscriptdays": "30",
        "maxscripts": 12,
        "createuser": "user",
        "createts": datetime(2026, 4, 27, 15, 8, 0),
        "reasoncode": "QTY LIMIT",
        "notes": "Three inhalers per 30 days: home, school and rescue kit documented.",
        "message": "PA APPROVED - QUANTITY LIMIT OVERRIDE",
        "source": "WEB",
        "authby": "DR. ROBERT THOMPSON",
        "quickcode": "QTY01",
        "appeal": "N",
        "reqreceived": date(2026, 4, 24),
        "documentation": date(2026, 4, 26),
        "reqapproved": date(2026, 4, 27),
        "memnotified": date(2026, 4, 28),
        "daysold": 3,
        "diagnosis": "J45.40 MODERATE PERSISTENT ASTHMA UNCOMPLICATED",
        "mpatype": "STANDARD",
        "reportingtype": "STANDARD",
        "basic_review_date": date(2026, 4, 27),
    },
    {
        "authnum": 1015,
        "subscribernum": "INS019",
        "groupnum": "GRP002",
        "personcodes": "01",
        "effdate": date(2026, 6, 15),
        "termdate": date(2026, 6, 15),
        "providerid": "0688517",
        "prescriberid": "1548930214",
        "ndc": "00074668001",
        "gpi": "28100010100310",
        "bg": "B",
        "action": "D",
        "genname": "LEVOTHYROXINE SODIUM",
        "brand": "SYNT",
        "createuser": "admin",
        "createts": datetime(2026, 6, 15, 9, 5, 0),
        "changeuser": "admin",
        "changets": datetime(2026, 6, 22, 14, 30, 0),
        "reasoncode": "STEP THER",
        "notes": "Denied: generic levothyroxine not trialed. Brand request may be resubmitted.",
        "message": "PA DENIED - STEP THERAPY NOT MET",
        "source": "FAX",
        "authby": "CLINICAL REVIEW",
        "appeal": "N",
        "denial": "03",
        "timeframe": "14",
        "reqreceived": date(2026, 6, 11),
        "documentation": date(2026, 6, 13),
        "memnotified": date(2026, 6, 17),
        "daysold": 4,
        "diagnosis": "E03.9 HYPOTHYROIDISM UNSPECIFIED",
        "mpatype": "STANDARD",
        "reportingtype": "STANDARD",
        "standard_review_date": date(2026, 6, 15),
    },
    {
        "authnum": 1016,
        "subscribernum": "INS020",
        "groupnum": "GRP003",
        "personcodes": "01",
        "effdate": date(2025, 4, 1),
        "termdate": date(2026, 3, 31),
        "providerid": "2400214",
        "prescriberid": "1659041325",
        "ndc": "00071015523",
        "gpi": "39400010100310",
        "bg": "G",
        "action": "A",
        "genname": "ATORVASTATIN CALCIUM",
        "refills": "11",
        "maxdailydose": "80",
        "maxscriptqty": "90",
        "maxscriptdays": "90",
        "maxscripts": 4,
        "createuser": "user",
        "createts": datetime(2025, 3, 27, 12, 15, 0),
        "changeuser": "user",
        "changets": datetime(2026, 4, 1, 7, 0, 0),
        "reasoncode": "QTY LIMIT",
        "notes": "High dose statin PA. Term reached, renewal not yet submitted.",
        "message": "PA EXPIRED",
        "source": "WEB",
        "authby": "DR. MICHAEL OBRIEN",
        "quickcode": "QTY01",
        "appeal": "N",
        "reqreceived": date(2025, 3, 25),
        "reqapproved": date(2025, 3, 27),
        "memnotified": date(2025, 3, 28),
        "daysold": 2,
        "diagnosis": "I25.10 ATHEROSCLEROTIC HEART DISEASE NATIVE ARTERY",
        "mpatype": "STANDARD",
        "reportingtype": "STANDARD",
        "basic_review_date": date(2025, 3, 27),
    },
    {
        "authnum": 1017,
        "subscribernum": "INS021",
        "groupnum": "GRP001",
        "personcodes": "01",
        "effdate": date(2026, 2, 1),
        "termdate": date(2026, 2, 28),
        "providerid": "1510388",
        "prescriberid": "1760152436",
        "ndc": "00093417401",
        "gpi": "01200010100320",
        "bg": "G",
        "action": "A",
        "genname": "AMOXICILLIN",
        "refills": "0",
        "maxdailydose": "1500",
        "maxscriptqty": "30",
        "maxscriptdays": "10",
        "maxscripts": 1,
        "createuser": "user",
        "createts": datetime(2026, 1, 30, 16, 42, 0),
        "changeuser": "user",
        "changets": datetime(2026, 3, 1, 7, 0, 0),
        "reasoncode": "ACUTE",
        "notes": "Single course for acute sinusitis. Expired, retained for history.",
        "message": "PA EXPIRED",
        "source": "PHONE",
        "authby": "DR. RACHEL DAVIS",
        "quickcode": "ACUTE1",
        "appeal": "N",
        "reqreceived": date(2026, 1, 29),
        "reqapproved": date(2026, 1, 30),
        "memnotified": date(2026, 1, 31),
        "daysold": 1,
        "diagnosis": "J01.90 ACUTE SINUSITIS UNSPECIFIED",
        "mpatype": "STANDARD",
        "reportingtype": "EXPEDITED",
        "basic_review_date": date(2026, 1, 30),
    },
    {
        "authnum": 1018,
        "subscribernum": "INS022",
        "groupnum": "GRP002",
        "personcodes": "01",
        "effdate": date(2026, 6, 1),
        "termdate": date(2027, 5, 31),
        "providerid": "2719045",
        "prescriberid": "1659041325",
        "ndc": "00591036305",
        "gpi": "33200030100310",
        "bg": "G",
        "action": "A",
        "genname": "AMLODIPINE BESYLATE",
        "refills": "11",
        "maxdailydose": "10",
        "maxscriptqty": "90",
        "maxscriptdays": "90",
        "maxscripts": 4,
        "createuser": "admin",
        "createts": datetime(2026, 5, 28, 10, 25, 0),
        "reasoncode": "OUT NET",
        "notes": "Out of network pharmacy allowed; nearest in-network site over 30 miles.",
        "message": "PA APPROVED - OUT OF NETWORK PHARMACY",
        "source": "PHONE",
        "authby": "DR. MICHAEL OBRIEN",
        "calledinby": "CARDIO CLINIC",
        "quickcode": "OON01",
        "appeal": "N",
        "reqreceived": date(2026, 5, 26),
        "reqapproved": date(2026, 5, 28),
        "memnotified": date(2026, 5, 29),
        "daysold": 2,
        "diagnosis": "I10 ESSENTIAL PRIMARY HYPERTENSION",
        "mpatype": "STANDARD",
        "reportingtype": "STANDARD",
        "basic_review_date": date(2026, 5, 28),
    },
    {
        "authnum": 1019,
        "subscribernum": "INS023",
        "groupnum": "GRP003",
        "personcodes": "01",
        "effdate": date(2026, 9, 1),
        "termdate": date(2027, 8, 31),
        "providerid": "1133402",
        "prescriberid": "1548930214",
        "ndc": "00093108256",
        "gpi": "27600030010320",
        "bg": "G",
        "genname": "METFORMIN HCL",
        "refills": "11",
        "maxdailydose": "2000",
        "maxscriptqty": "180",
        "maxscriptdays": "90",
        "maxscripts": 4,
        "createuser": "user",
        "createts": datetime(2026, 8, 7, 9, 30, 0),
        "reasoncode": "QTY LIMIT",
        "notes": "New 90 day supply request submitted through portal, not yet reviewed.",
        "message": "PA PENDING - CLINICAL REVIEW",
        "source": "WEB",
        "calledinby": "ENDO CLINIC",
        "appeal": "N",
        "reqreceived": date(2026, 8, 7),
        "daysold": 3,
        "diagnosis": "E11.9 TYPE 2 DIABETES MELLITUS WITHOUT COMPLICATIONS",
        "mpatype": "STANDARD",
        "reportingtype": "STANDARD",
    },
    {
        "authnum": 1020,
        "subscribernum": "INS024",
        "groupnum": "GRP001",
        "personcodes": "01",
        "effdate": date(2026, 7, 1),
        "termdate": date(2027, 6, 30),
        "providerid": "5402891",
        "prescriberid": "1760152436",
        "ndc": "00781505701",
        "gpi": "28100010100315",
        "bg": "G",
        "action": "A",
        "genname": "LEVOTHYROXINE SODIUM",
        "refills": "11",
        "maxdailydose": "0.15",
        "maxscriptqty": "90",
        "maxscriptdays": "90",
        "maxscripts": 4,
        "createuser": "admin",
        "createts": datetime(2026, 6, 26, 13, 12, 0),
        "reasoncode": "QTY LIMIT",
        "notes": "90 day supply approved; TSH stable on current dose for two consecutive draws.",
        "message": "PA APPROVED - QUANTITY LIMIT OVERRIDE",
        "source": "WEB",
        "authby": "DR. RACHEL DAVIS",
        "quickcode": "QTY01",
        "appeal": "N",
        "reqreceived": date(2026, 6, 23),
        "documentation": date(2026, 6, 25),
        "reqapproved": date(2026, 6, 26),
        "memnotified": date(2026, 6, 27),
        "daysold": 3,
        "diagnosis": "E03.9 HYPOTHYROIDISM UNSPECIFIED",
        "mpatype": "STANDARD",
        "reportingtype": "STANDARD",
        "basic_review_date": date(2026, 6, 26),
    },
)

_COLUMNS = tuple(c.name for c in _prior_auths.columns if c.name != "id")


def _existing_authnums(bind) -> set[int]:
    rows = bind.execute(sa.text("SELECT authnum FROM prior_auths")).fetchall()
    return {int(authnum) for (authnum,) in rows if authnum is not None}


def upgrade() -> None:
    bind = op.get_bind()
    existing = _existing_authnums(bind)

    rows = []
    for seed in _SEED:
        if int(seed["authnum"]) in existing:
            continue
        row = {column: seed.get(column) for column in _COLUMNS}
        row["id"] = uuid.uuid4()
        rows.append(row)

    if rows:
        op.bulk_insert(_prior_auths, rows)


def downgrade() -> None:
    bind = op.get_bind()
    bind.execute(
        _prior_auths.delete().where(
            _prior_auths.c.authnum.in_([seed["authnum"] for seed in _SEED])
        )
    )
