"""auth table primary key fixed

Revision ID: bc8958dad29d
Revises: 1e8919eea626
Create Date: 2026-06-19 13:03:58.435770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bc8958dad29d'
down_revision: Union[str, Sequence[str], None] = '1e8919eea626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_revoked_access_tokens_token_hash'), 'revoked_access_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revoked_access_tokens_token_hash'), table_name='revoked_access_tokens')
    # ### end Alembic commands ###
