"""add subscriber lookup table

Revision ID: fb380cc4a6a2
Revises: 6aec3e73d0c2
Create Date: 2026-08-19 14:24:09.788592

Creates SUBSCRIBER in whatever schema the app's DB user defaults to (same
pattern as 6aec3e73d0c2). Split into its own revision rather than folded
into 6aec3e73d0c2 because that revision was already applied to this dev
database (SUBSCRIBERGROUPLIST/SUBSCRIBERELIGLIST already hold seeded rows),
so editing its upgrade() in place would never actually run against the DB.

Column shapes match the Subscriber class in app/models/member_model.py
exactly, mirroring the real SQLMGR SUBSCRIBER table DDL.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb380cc4a6a2'
down_revision: Union[str, Sequence[str], None] = '6aec3e73d0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "SUBSCRIBER",
        sa.Column("SUBSCRIBERNUM", sa.String(length=45), nullable=False),
        sa.Column("PERSONCODE", sa.String(length=2), nullable=False),
        sa.Column("CLIENTCODE", sa.String(length=10), nullable=False),
        sa.Column("SSN", sa.String(length=9), nullable=True),
        sa.Column("LASTNAME", sa.String(length=25), nullable=True),
        sa.Column("FIRSTNAME", sa.String(length=25), nullable=True),
        sa.Column("MI", sa.String(length=1), nullable=True),
        sa.Column("ADDR1", sa.String(length=55), nullable=True),
        sa.Column("ADDR2", sa.String(length=55), nullable=True),
        sa.Column("CITY", sa.String(length=20), nullable=True),
        sa.Column("STATE", sa.String(length=2), nullable=True),
        sa.Column("ZIP", sa.String(length=11), nullable=True),
        sa.Column("HOMEPHONE", sa.String(length=10), nullable=True),
        sa.Column("WORKPHONE", sa.String(length=10), nullable=True),
        sa.Column("DOB", sa.DateTime(), nullable=True),
        sa.Column("TERMINATION", sa.DateTime(), nullable=True),
        sa.Column("STATUS", sa.String(length=1), nullable=True),
        sa.Column("GENDER", sa.String(length=1), nullable=True),
        sa.Column("CARRIER", sa.String(length=10), nullable=True),
        sa.Column("LOCATION", sa.String(length=10), nullable=True),
        sa.Column("UPDATETS", sa.DateTime(), nullable=True),
        sa.Column("DATEENTERED", sa.DateTime(), nullable=True),
        sa.Column("CARDDATE", sa.DateTime(), nullable=True),
        sa.Column("NUMCARDS", sa.Integer(), nullable=True),
        sa.Column("TESTONLY", sa.Integer(), nullable=True),
        sa.Column("INJDATE", sa.DateTime(), nullable=True),
        sa.Column("INJTYPE", sa.String(length=30), nullable=True),
        sa.Column("BROKER1", sa.String(length=10), nullable=True),
        sa.Column("BROKER2", sa.String(length=10), nullable=True),
        sa.Column("EMPLOYERNAME", sa.String(length=40), nullable=True),
        sa.Column("EMPLOYERADDR1", sa.String(length=40), nullable=True),
        sa.Column("EMPLOYERADDR2", sa.String(length=40), nullable=True),
        sa.Column("EMPLOYERCITY", sa.String(length=20), nullable=True),
        sa.Column("EMPLOYERSTATE", sa.String(length=2), nullable=True),
        sa.Column("EMPLOYERZIP", sa.String(length=11), nullable=True),
        sa.Column("ADJUSTER", sa.String(length=25), nullable=True),
        sa.Column("VENUESTATE", sa.String(length=2), nullable=True),
        sa.Column("INJCAUSE", sa.String(length=100), nullable=True),
        sa.Column("CLAIMID", sa.String(length=30), nullable=True),
        sa.Column("COPAYBANKAMT", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("COPAYBANKTYPE", sa.String(length=10), nullable=True),
        sa.Column("CHARGECARDNUM", sa.String(length=20), nullable=True),
        sa.Column("CHARGECARDEXP", sa.String(length=8), nullable=True),
        sa.Column("CHARGECARDNAME", sa.String(length=25), nullable=True),
        sa.Column("EMAILADDRESS", sa.String(length=50), nullable=True),
        sa.Column("TRANSITNUM", sa.String(length=20), nullable=True),
        sa.Column("ACCOUNTNUM", sa.String(length=20), nullable=True),
        sa.Column("CARDSTATUS", sa.String(length=2), nullable=True),
        sa.Column("CARDSTATUSDATE", sa.DateTime(), nullable=True),
        sa.Column("PCP", sa.String(length=100), nullable=True),
        sa.Column("FLEX2", sa.String(length=10), nullable=True),
        sa.Column("FLEX3", sa.String(length=10), nullable=True),
        sa.Column("EMPCD", sa.String(length=2), nullable=True),
        sa.Column("NOUPDATE", sa.String(length=1), nullable=True),
        sa.Column("ADDEDBY", sa.String(length=30), nullable=True),
        sa.Column("MBRSINCE", sa.DateTime(), nullable=True),
        sa.Column("STR1_20", sa.String(length=20), nullable=True),
        sa.Column("STR2_20", sa.String(length=20), nullable=True),
        sa.Column("STR1_04", sa.String(length=4), nullable=True),
        sa.Column("STR1_15", sa.String(length=15), nullable=True),
        sa.Column("STR2_04", sa.String(length=4), nullable=True),
        sa.Column("STR2_15", sa.String(length=15), nullable=True),
        sa.Column("RELCODE", sa.String(length=2), nullable=True),
        sa.Column("ELIGOVERRIDE", sa.String(length=2), nullable=True),
        sa.Column("STR3_20", sa.String(length=20), nullable=True),
        sa.Column("STR1_01", sa.String(length=1), nullable=True),
        sa.Column("STR2_01", sa.String(length=1), nullable=True),
        sa.Column("STR1_05", sa.String(length=5), nullable=True),
        sa.Column("STR1_10", sa.String(length=10), nullable=True),
        sa.Column("FLEX1", sa.String(length=10), nullable=True),
        sa.Column("STR1_02", sa.String(length=2), nullable=True),
        sa.Column("PREVIOUSCARDID", sa.String(length=45), nullable=True),
        sa.Column("ALTCARDID", sa.String(length=45), nullable=True),
        sa.Column("ENROLLTYPE", sa.String(length=3), nullable=True),
        sa.Column("ENROLLNABP", sa.String(length=12), nullable=True),
        sa.Column("SOURCE", sa.String(length=10), nullable=True),
        sa.Column("AUTHBY", sa.String(length=50), nullable=True),
        sa.Column("NONHIPPAID", sa.String(length=18), nullable=True),
        sa.Column("MFNAME", sa.String(length=20), nullable=True),
        sa.Column("CARDPRINTDATE", sa.DateTime(), nullable=True),
        sa.Column("PCPPHONE", sa.String(length=15), nullable=True),
        sa.Column("LEGALREP", sa.String(length=1), nullable=True),
        sa.Column("CUSTACT", sa.String(length=1), nullable=True),
        sa.Column("ACTIVATIONDATE", sa.DateTime(), nullable=True),
        sa.Column("PRIMARYPHARM", sa.String(length=50), nullable=True),
        sa.Column("PRIPHARMPHONE", sa.String(length=10), nullable=True),
        sa.Column("PRIPHARMFAX", sa.String(length=10), nullable=True),
        sa.Column("BOOKLETDATE", sa.DateTime(), nullable=True),
        sa.Column("BOOKLETPRINTDATE", sa.DateTime(), nullable=True),
        sa.Column("COUNTRY", sa.String(length=75), nullable=True),
        sa.Column("STR1_50", sa.String(length=50), nullable=True),
        sa.Column("EMPLOYERPHONE", sa.String(length=10), nullable=True),
        sa.Column("EMPLOYERFAX", sa.String(length=10), nullable=True),
        sa.Column("ADJUSTERPHONE", sa.String(length=10), nullable=True),
        sa.Column("ADJUSTERFAX", sa.String(length=10), nullable=True),
        sa.Column("BITFLAGS", sa.Integer(), nullable=True),
        sa.Column("EXTELIGNEXT", sa.DateTime(), nullable=True),
        sa.Column("EXTELIGLAST", sa.DateTime(), nullable=True),
        sa.Column("FACILITY", sa.String(length=50), nullable=True),
        sa.Column("PCPFAX", sa.String(length=10), nullable=True),
        sa.Column("ADJUSTEREMAIL", sa.String(length=50), nullable=True),
        sa.Column("MAILADDR1", sa.String(length=50), nullable=True),
        sa.Column("MAILADDR2", sa.String(length=50), nullable=True),
        sa.Column("MAILCITY", sa.String(length=20), nullable=True),
        sa.Column("MAILSTATE", sa.String(length=2), nullable=True),
        sa.Column("MAILZIP", sa.String(length=11), nullable=True),
        sa.Column("CARDAPC", sa.String(length=2), nullable=True),
        sa.Column("CARDBPC", sa.String(length=2), nullable=True),
        sa.Column("PCPID", sa.String(length=50), nullable=True),
        sa.Column("PCPGROUP", sa.String(length=100), nullable=True),
        sa.Column("ETHNICITY", sa.String(length=2), nullable=True),
        sa.Column("RACE", sa.String(length=2), nullable=True),
        sa.Column("ISSUERASSIGNEDMEMID", sa.String(length=45), nullable=True),
        sa.Column("ISSUERASSIGNEDSUBID", sa.String(length=20), nullable=True),
        sa.Column("PRIORINSCARRIERID", sa.String(length=20), nullable=True),
        sa.Column("LASTPREMIUMPAIDDATE", sa.DateTime(), nullable=True),
        sa.Column("RELATIONSHIPDESC", sa.String(length=45), nullable=True),
        sa.Column("MAILFIRSTNAME", sa.String(length=25), nullable=True),
        sa.Column("MAILLASTNAME", sa.String(length=25), nullable=True),
        sa.Column("MAILPRIMARYPHONE", sa.String(length=12), nullable=True),
        sa.Column("MAILSECONDARYPHONE", sa.String(length=12), nullable=True),
        sa.Column("CASEMANAGER", sa.String(length=75), nullable=True),
        sa.Column("ADJUSTEREXT", sa.String(length=10), nullable=True),
        sa.Column("MPRWC1", sa.String(length=2), nullable=True),
        sa.Column("MPRWC2", sa.String(length=2), nullable=True),
        sa.Column("MPRWC3", sa.String(length=2), nullable=True),
        sa.Column("GPENTERDATE", sa.DateTime(), nullable=True),
        sa.Column("GPPERIODSEG", sa.String(length=2), nullable=True),
        sa.Column("STR3_01", sa.String(length=1), nullable=True),
        sa.Column("STR2_50", sa.String(length=50), nullable=True),
        sa.Column("STR3_50", sa.String(length=50), nullable=True),
        sa.Column("LANGSPOKEN", sa.String(length=20), nullable=True),
        sa.Column("LANGPRINT", sa.String(length=5), nullable=True),
        sa.Column("MEDAIDCODE", sa.String(length=2), nullable=True),
        sa.Column("CLIENTPC", sa.String(length=3), nullable=True),
        sa.Column("DEPENDENCYRESTART", sa.DateTime(), nullable=True),
        sa.Column("GPTERMDATE", sa.DateTime(), nullable=True),
        sa.Column("STR1_90", sa.String(length=90), nullable=True),
        sa.Column("STR2_90", sa.String(length=90), nullable=True),
        sa.Column("BENYRSTARTOVERRIDE", sa.DateTime(), nullable=True),
        sa.Column("DEPENDENCYLKBKDAYS", sa.Integer(), nullable=True),
        sa.Column("DATEOFDEATH", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("SUBSCRIBERNUM", "PERSONCODE", "CLIENTCODE"),
    )


def downgrade() -> None:
    op.drop_table("SUBSCRIBER")
