from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import Date, DateTime, Index, Numeric, String
from sqlalchemy.orm import Mapped, mapped_column

from app.database.base import Base


class PriorAuthModel(Base):
    __tablename__ = "prior_auths"

    __table_args__ = (
        Index("ix_prior_auths_subscribernum_groupnum", "subscribernum", "groupnum"),
        Index("ix_prior_auths_ndc", "ndc"),
        Index("ix_prior_auths_gpi", "gpi"),
        Index("ix_prior_auths_effdate_termdate", "effdate", "termdate"),
    )

    authnum: Mapped[Decimal] = mapped_column(
        Numeric, unique=True, index=True, nullable=False
    )
    subscribernum: Mapped[str | None] = mapped_column(String(45), nullable=True)
    groupnum: Mapped[str | None] = mapped_column(String(20), nullable=True)
    personcodes: Mapped[str | None] = mapped_column(String(50), nullable=True)
    effdate: Mapped[date | None] = mapped_column(Date, nullable=True)
    termdate: Mapped[date | None] = mapped_column(Date, nullable=True)
    providerid: Mapped[str | None] = mapped_column(String(30), nullable=True)
    prescriberid: Mapped[str | None] = mapped_column(String(15), nullable=True)
    ndc: Mapped[str | None] = mapped_column(String(11), nullable=True)
    gpi: Mapped[str | None] = mapped_column(String(14), nullable=True)
    bg: Mapped[str | None] = mapped_column(String(1), nullable=True)
    action: Mapped[str | None] = mapped_column(String(1), nullable=True)
    bitflags: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    treatmony: Mapped[str | None] = mapped_column(String(1), nullable=True)
    costhandler: Mapped[str | None] = mapped_column(String(20), nullable=True)
    dispfeehandler: Mapped[str | None] = mapped_column(String(20), nullable=True)
    copayhandler: Mapped[str | None] = mapped_column(String(20), nullable=True)
    brandflatcopay: Mapped[str | None] = mapped_column(String(10), nullable=True)
    genericflatcopay: Mapped[str | None] = mapped_column(String(10), nullable=True)
    treatpharmnet: Mapped[str | None] = mapped_column(String(30), nullable=True)
    treatphysnet: Mapped[str | None] = mapped_column(String(20), nullable=True)
    maxdailydose: Mapped[str | None] = mapped_column(String(5), nullable=True)
    maxscriptqty: Mapped[str | None] = mapped_column(String(10), nullable=True)
    maxscriptdays: Mapped[str | None] = mapped_column(String(5), nullable=True)
    maxscriptdollars: Mapped[str | None] = mapped_column(String(10), nullable=True)
    createuser: Mapped[str | None] = mapped_column(String(20), nullable=True)
    createts: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    changeuser: Mapped[str | None] = mapped_column(String(20), nullable=True)
    changets: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    reasoncode: Mapped[str | None] = mapped_column(String(20), nullable=True)
    notes: Mapped[str | None] = mapped_column(String(4000), nullable=True)
    deaclass: Mapped[str | None] = mapped_column(String(9), nullable=True)
    ignorepm: Mapped[str | None] = mapped_column(String(55), nullable=True)
    genname: Mapped[str | None] = mapped_column(String(60), nullable=True)
    therclass: Mapped[str | None] = mapped_column(String(10), nullable=True)
    refills: Mapped[str | None] = mapped_column(String(4), nullable=True)
    message: Mapped[str | None] = mapped_column(String(100), nullable=True)
    source: Mapped[str | None] = mapped_column(String(10), nullable=True)
    authby: Mapped[str | None] = mapped_column(String(50), nullable=True)
    includepm: Mapped[str | None] = mapped_column(String(55), nullable=True)
    includepmcolor: Mapped[str | None] = mapped_column(String(1), nullable=True)
    rxotcind: Mapped[str | None] = mapped_column(String(1), nullable=True)
    mark: Mapped[str | None] = mapped_column(String(10), nullable=True)
    calledinby: Mapped[str | None] = mapped_column(String(50), nullable=True)
    quickcode: Mapped[str | None] = mapped_column(String(10), nullable=True)
    tierset: Mapped[str | None] = mapped_column(String(1), nullable=True)
    appeal: Mapped[str | None] = mapped_column(String(3), nullable=True)
    denial: Mapped[str | None] = mapped_column(String(2), nullable=True)
    timeframe: Mapped[str | None] = mapped_column(String(2), nullable=True)
    reqreceived: Mapped[date | None] = mapped_column(Date, nullable=True)
    documentation: Mapped[date | None] = mapped_column(Date, nullable=True)
    reqapproved: Mapped[date | None] = mapped_column(Date, nullable=True)
    memnotified: Mapped[date | None] = mapped_column(Date, nullable=True)
    daysold: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    maxscripts: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    reportingndc: Mapped[str | None] = mapped_column(String(11), nullable=True)
    reportingphys: Mapped[str | None] = mapped_column(String(15), nullable=True)
    mincouponvalue: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    maxcouponvalue: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    maxdawamt: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    mincouponcopay: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    sdc: Mapped[str | None] = mapped_column(String(20), nullable=True)
    eocid: Mapped[str | None] = mapped_column(String(11), nullable=True)
    dawpercent: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    mischandler: Mapped[str | None] = mapped_column(String(20), nullable=True)
    mpatype: Mapped[str | None] = mapped_column(String(25), nullable=True)
    bitflags2: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    ignoremischandler: Mapped[str | None] = mapped_column(String(20), nullable=True)
    ignorepm2: Mapped[str | None] = mapped_column(String(55), nullable=True)
    ignorepm3: Mapped[str | None] = mapped_column(String(55), nullable=True)
    manualgenname: Mapped[str | None] = mapped_column(String(70), nullable=True)
    maxmpascripts: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    subgroup: Mapped[str | None] = mapped_column(String(20), nullable=True)
    batchbitflags: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    origgroupnum: Mapped[str | None] = mapped_column(String(20), nullable=True)
    couponds: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    couponuses: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    maxamtunit: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    totalqtypercoupon: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    hicn: Mapped[str | None] = mapped_column(String(20), nullable=True)
    origcontractid: Mapped[str | None] = mapped_column(String(20), nullable=True)
    origpbp: Mapped[str | None] = mapped_column(String(4), nullable=True)
    setclaimtag: Mapped[str | None] = mapped_column(String(200), nullable=True)
    compoundcode: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    reportingcui: Mapped[str | None] = mapped_column(String(7), nullable=True)
    diagnosis: Mapped[str | None] = mapped_column(String(100), nullable=True)
    ingstrength: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    bitflags3: Mapped[Decimal | None] = mapped_column(Numeric(38, 0), nullable=True)
    minscriptqty: Mapped[Decimal | None] = mapped_column(Numeric(10, 3), nullable=True)
    minscriptdays: Mapped[Decimal | None] = mapped_column(Numeric(3, 0), nullable=True)
    ignoreduringr: Mapped[str | None] = mapped_column(String(24), nullable=True)
    basic_review_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    standard_review_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    complex_review_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    rereview_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    no_charge_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    internal_appeal_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    brand: Mapped[str | None] = mapped_column(String(4), nullable=True)
    reportingtype: Mapped[str | None] = mapped_column(String(15), nullable=True)
    proffeehandler: Mapped[str | None] = mapped_column(String(20), nullable=True)
    displimitshandler: Mapped[str | None] = mapped_column(String(20), nullable=True)
    seconddiagnosis: Mapped[str | None] = mapped_column(String(100), nullable=True)
