ACCESS_TOKEN_EXPIRE_SECONDS = 900         # 15 min
REFRESH_TOKEN_EXPIRE_DAYS  = 1
REFRESH_TOKEN_REMEMBER_ME_DAYS = 30

ALGORITHM = "HS256"

# HTTP header names
CORRELATION_ID_HEADER = "X-Correlation-ID"
REQUEST_ID_HEADER     = "X-Request-ID"
